### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by maolike** [google/UIforETW#165]
## Why UI Delays has no data?What should i set in UIForETW?
![image](https://github.com/google/UIforETW/assets/40014595/988b9b4b-623c-4c68-b7aa-d112ed3ebad7)

**Comment by randomascii** [comment]
If UI delays has no data that may mean that there were no UI delays in the trace that you recorded. That is, maybe all processes continued pumping messages.

That seems unlikely, but it is possible. Unfortunately this is really a Windows/ETW question, not a UIforETW question, so you might want to try asking on stack overflow or similar for ideas.

**Comment by maolike** [comment]
Thank you for your answer.
In my scenario, VS was stuck first, and then the entire desktop was stuck.I closed VS via ghost window,then clicked  button of "Save Trace Buffers" in UIforETW.
I set circular buffer tracing in UIforETW.Could it be that the previous data has been overwritten, causing UI delays to have no data? Normally, UI delays will definitely have devenv.exe data.

**Comment by randomascii** [comment]
That does sound frustrating, and it sounds like a bug. The circular buffer that holds the UI delays data normally covers an extremely long period of time because the data rate is quite low. You can usually infer from the timeline how long a period that buffer covered (see where the CPU data is, and then see how much longer the overall timeline is) but that doesn't help you do anything. Sorry, that's all I've got.

**Comment by maolike** [comment]
Anyway, thanks for your tool and blog.
I finally solved the problem by tracing to file.The VS hanging was caused by the Sogou Pinyin.I switched the input method to Microsoft input method and it became normal.
