### ISSUE TITLE
Question about pidsByType

### ISSUE THREAD

**Issue by ariccio** [google/UIforETW#26]
[`pidsByType` is a `std::map`](https://github.com/google/UIforETW/blob/master/UIforETW/UIforETWDlg.cpp#L1648)

Does it need to be ordered? If not, then a `std::map` is a waste of effort over a `std::unordered_map`.

#nitpicking

**Comment by randomascii** [comment]
I don't think so. But std::map is less typing, and the performance difference would not be relevant..

I think the only code in UIforETW that is performance sensitive right now is the working-set monitoring code. In my tests it usually takes 50 ms, which is a lot for something that runs once a second. I optimized it a bit but now all the time is spent in Microsoft's code.

**Comment by ariccio** [comment]
I'll have to take a look at the working set monitoring code.

**Comment by randomascii** [comment]
Sure, cool. I wouldn't be surprised if InitializeProcessForWsWatch() didn't
improve the performance.

One cool thing is that UIforETW actually profiles itself every time you
record a trace. The CPU consumption burps from monitoring the working set
are quite obvious. It could be made more friendly by printing the elapsed
time with outputPrintf so that improvements are more obvious.

Also, I just realized that working-set monitoring continues even when no
trace is being recorded. That's wasteful.

On Wed, May 13, 2015 at 2:32 PM, Alexander Riccio <notifications@github.com>
wrote:

> I'll have to take a look at the working set monitoring code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/UIforETW/issues/26#issuecomment-101822426>.
>



-- 
Bruce Dawson

**Comment by ariccio** [comment]
>   It could be made more friendly by printing the elapsed time with outputPrintf so that improvements are more obvious.

By the way: I still don't understand why we pass `\n`-style ␤ to `outputPrintf`, only to translate it to `\r\n` style ␤? Why not just pass `\r\n` in the first place?

**Comment by randomascii** [comment]
Off the top of my head I'd say that \n line endings are standard.
outputPrintf fixes them so that the stupid edit control can handle the
strings. The rest of the project shouldn't need to be corrupted because of
the edit control.

Same reason that printf defaults to doing the translation.

On Wed, May 13, 2015 at 3:39 PM, Alexander Riccio <notifications@github.com>
wrote:

> It could be made more friendly by printing the elapsed time with
> outputPrintf so that improvements are more obvious.
>
> By the way: I still don't understand why we pass \n-style ␤ to
> outputPrintf, only to translate it to \r\n style ␤? Why not just pass \r\n
> in the first place?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/UIforETW/issues/26#issuecomment-101839157>.
>



-- 
Bruce Dawson

**Comment by ariccio** [comment]
Uggh. Well, uh, ok.

It doesn't make a measurable difference, but I do have ideological reservations about it - doing work at runtime that we could instead do before (even) compile-time by hitting an extra two keys.

I guess I can put up with that.

**Comment by ariccio** [comment]
> One cool thing is that UIforETW actually profiles itself every time you record a trace.

Whoa. Inception.

**Comment by randomascii** [comment]
It's profilers all the way down.

And why not, I've use ETW to profile WPA and xperf several times, so why
not UIforETW?

On Wed, May 13, 2015 at 4:12 PM, Alexander Riccio <notifications@github.com>
wrote:

> One cool thing is that UIforETW actually profiles itself every time you
> record a trace.
>
> Whoa. Inception.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/UIforETW/issues/26#issuecomment-101845223>.
>



-- 
Bruce Dawson

**Comment by ariccio** [comment]
Nothing wrong with it, it's just pretty cool.

**Comment by randomascii** [comment]
Yep. It makes me smile every time I do it.

On Wed, May 13, 2015 at 5:41 PM, Alexander Riccio <notifications@github.com>
wrote:

> Nothing wrong with it, it's just pretty cool.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/UIforETW/issues/26#issuecomment-101865998>.
>



-- 
Bruce Dawson
