### ISSUE TITLE
Server Core 2008 Compat

### ISSUE THREAD

**Issue by k-y** [google/UIforETW#59]
We have a couple of systems where we've been running ETW tracing recently and our Server Core 2008 platform wasn't able to install UIforETW out-of-the-box and complained that oledlg.dll was required.

**Comment by randomascii** [comment]
How did you try installing UIforETW? And where did the failure occur?

The UIforETW releases should run (I believe) down to Vista level, although ETW tracing doesn't really become useful until Windows 7, which is equivalent to Server 2008 R2. So, even if you got UIforETW running on Server Core 2008 it wouldn't work well.

The WPT installers may be failing also. Most likely the WPT 10 installer is failing. UIforETW can run without WPT 10 being installed as long as WPT 8.1 is installed. Can you check in "c:\Program Files (x86)\Windows Kits" to see if "8.1\Windows Performance Toolkit" or "10\Windows Performance Toolkit" exist?

But, as I say, ETW tracing on Server 2008 is not worth it.

**Comment by k-y** [comment]
Sorry, I wasn't being clear.  We do use 2008 R2.  I managed to get the 32-bit oledlg.dll copied over and UIforETW32.exe works; just can't get the 64-bit version working.

**Comment by mwinterb** [comment]
@randomascii:
oledlg.dll isn't included in the "Core" editions of Windows Server. MFC has a dependency on oledlg for a few functions, looking at UIforETW with Depends, it's OleUIBusy. The DLL builds of MFC have oledlg.dll marked as delay loaded, but since the github release of UIforETW links statically, it doesn't get the delay load magic automatically. Of course, if that's changed to be delay loaded and UIforETW ever indirectly hits that, then UIforETW will crash. If it's feasible, it seems like avoiding the dependency entirely would be better.

I haven't done a full test of UIforETW after this change, but it looks like removing the call to [AfxEnableControlContainer](https://msdn.microsoft.com/en-us/library/x1se4y1y.aspx) from CUIforETWApp::InitInstance ends up removing the dependency on oledlg. Was the call to AfxEnableControlContainer present just from AppWizard stuff or does UIforETW actually depend on it? Even after removing that, there may be other system DLLs that UIforETW depends on that aren't available in Server Core (I don't have one to test with right now).

Here's a list of the APIs that are available in Server 2008 R2:
https://msdn.microsoft.com/en-us/library/ee391633(v=vs.85).aspx
It doesn't include gdi32.dll, but that seems crazy since user32 and comctl32 are available, so the list may not be accurate. These are the DLLs that aren't on that list that UIforETW depends on directly: gdi32, GdiPlus, MsImg32, UxTheme, oleacc, winmm.

**Comment by randomascii** [comment]
Fascinating. Thanks for the detailed analysis @mwinterb. I can see if AfxEnableControlContainer() is needed - probably not. Almost certainly not.

@k-y - UIforETW32.exe will work fine for most purposes. The 64-bit version is only needed for monitoring the working sets of other processes, and even then only for the 'expensive' variant that is rarely used. So, if UIforETW32 is working, use it.

**Comment by mwinterb** [comment]
The gdiplus, msimg32, and winmm dependencies are all because of the [MFC feature pack stuff that was licensed from BCG](http://blogs.msdn.com/b/vcblog/archive/2008/04/07/mfc-update-powered-by-bcgsoft.aspx). CDialogEx, CWinAppEx, the CMFC controls, and the VisualManagers are all part of that. The code isn't isolated very well so one reference brings in seemingly everything. There's a [slightly hacky way](http://blogs.msdn.com/b/vcblog/archive/2012/02/06/10263387.aspx) of opting out of those classes and the static build also drops 2MB in size, but the flag is only effective when linking statically to MFC. So a dependency could be added but consequences wouldn't be known until the release is made, so it may not be worth it. Doubly so if removing the call to AfxEnableControlContainer is enough to get Server Core support. 112142e7816798444e747628689f21681f73b694 removed the only useful dependency that I'm aware of, and with the change everything seems to behave normal when clicking around the dialogs. CDialogEx and CShellManager are still used, but I don't know if we're presently gaining anything by using them.

Banning the usage of those controls does limit the future UI development of UIforETW so that's another con of doing that change.

**Comment by randomascii** [comment]
Call removed. I haven't updated the release. Note that you can rebuild no releases with package_etw.bat.

**Comment by randomascii** [comment]
I tried doing this:

#define _AFX_NO_MFC_CONTROLS_IN_DIALOGS 

but the static builds hit some linker errors:

1>uafxcw.lib(afxctrlcontainer2.obj) : error LNK2005: "void __cdecl AfxRegisterMFCCtrlClasses(void)" (?AfxRegisterMFCCtrlClasses@@YAXXZ) already defined in afxnmcd.lib(afxctrlcontainer2.obj)
1>uafxcw.lib(afxctrlcontainer2.obj) : error LNK2005: "protected: void __thiscall CMFCControlContainer::PreUnsubclassControl(class CWnd *)" (?PreUnsubclassControl@CMFCControlContainer@@IAEXPAVCWnd@@@Z) already defined in afxnmcd.lib(afxctrlcontainer2.obj)
1>uafxcw.lib(afxctrlcontainer2.obj) : error LNK2005: "public: int __thiscall CMFCControlContainer::SubclassDlgControls(void)" (?SubclassDlgControls@CMFCControlContainer@@QAEHXZ) already defined in afxnmcd.lib(afxctrlcontainer2.obj)
1>C:\github\UIforETW\UIforETW\..\bin\UIforETWStatic_devrel32.exe : fatal error LNK1169: one or more multiply defined symbols found

I'd be happy to accept pull requests that resolve this. Limiting future UI development isn't a concern - portability to server SKUs is more important than a fancy UI. Shrinking the size of the static builds would be a nice bonus, but reducing the required DLLs is more important.

**Comment by mwinterb** [comment]
Done in #60.

Unrelated, but I mildly wonder how much Z regrets his choice in account name.

**Comment by randomascii** [comment]
I just uploaded release v1.24 that contains the change from PR #60. Give it a try. etwpackage.zip is now 1.7 MB smaller and uses four (or is it five?) fewer DLLs.

**Comment by randomascii** [comment]
Is this resolved now?

**Comment by k-y** [comment]
Yup, I tested this with our core servers.  Thanks again!
