### ISSUE TITLE
Error? Not sure

### ISSUE THREAD

**Issue by modulexcite** [google/UIforETW#79]
Whenever I start/stop a trace, it's trying to rename the Amcache.hve file but it's inadvertently failing to do so. I understand from the release notes that this is by design to reduce the startup delay with XPerf. I do have the admin permissions on the system but the file is in use by the "System" process preventing the UIforETW application to rename the file.

Below is the message in the log window.
---
Failed to rename C:\Windows\AppCompat\Programs\Amcache.hve to C:\Windows\AppCompat\Programs\Amcache_temp.hve
---

**Comment by randomascii** [comment]
The renaming of amcache.hve is a hack which improves trace saving (not startup) times on *some* machines. I don't know what machines it will help so I always try renaming. It also fails on my machines but I just ignore the error message. I could:

1) Remove (or reword) the warning message since it is more confusing than helpful.
2) Stop even trying to rename amcache.hve.
3) Only try renaming amcache.hve on older versions of Windows (I originally saw the problem on Windows 7)

They're all easy enough to do. I don't know for sure which is appropriate because I don't really understand the bug that I'm working around.

But, feel free to ignore the message.

**Comment by modulexcite** [comment]
Great thanks for the explanation and the excellent tool. Also IMHO, I think a demo(screen capture) of the tool tracing a process would be helpful to new users.You rock!


    _____________________________

**Comment by modulexcite** [comment]
I forgot to mention that I was using a Windows 7 64-bit machine, so I don't think renaming it on only older versions of Windows works. I'm not sure about vista and below.

___________________________
Thanks.

    _____________________________

**Comment by randomascii** [comment]
ETW doesn't even really work on Vista and below so I ignore them. I'll probably just delete the message, or make it far more subtle, since it adds some confusion but probably no value.

I should do a demo video - good idea. It's too bad that my existing training videos (https://randomascii.wordpress.com/2014/08/19/etw-training-videos-available-now/) predate UIforETW.

**Comment by modulexcite** [comment]
ok thanks.

**Comment by randomascii** [comment]
Message removed in 19e2b8b6c57bf9b45f5507b15c9dffa14010accb.
