### ISSUE TITLE
Need support 3rd profiles

### ISSUE THREAD

**Issue by BianChengNan** [google/UIforETW#93]
Is there any plan to support additional profiles (or has supported?)? just like **WPRUI**'s **Add Profiles...** function! That's quit convenient and necessary! thanks very very much!

**Comment by randomascii** [comment]
It could be valuable to have a way to load a configuration file that would adjust the varied settings (extra kernel flags, perf counters, user-mode-providers, etc.) so that UIforETW could be more easily used by non-technical users. But, I don't have much enthusiasm for doing this work myself. So, unless somebody else volunteers it will have to continue being manual configuration, with default settings that make manual configuration as rarely needed as possible.
